### ISSUE TITLE
Kullanılacak fontlar

### ISSUE THREAD

**Issue by echojanz** [echojanz/qoutte#1]
Abel|Abril+Fatface|Arimo|Arvo|Barlow:500|Berkshire+Swash|Bitter|Bree+Serif|Cabin|Cabin+Sketch|Catamaran|Coustard|Crimson+Text:600|Didact+Gothic|Domine|Fauna+One|Faustina|Grand+Hotel|Hind|Karla|Lato:700|Leckerli+One|Libre+Baskerville|Lora|Lustria|Merriweather:700|Montserrat:700|Muli:200|Nunito:600|Oswald|Oxygen|PT+Sans:700|PT+Serif:700|Patua+One|Permanent+Marker|Playfair+Display:700i|Poppins:500|Prata|Quicksand|Raleway|Roboto+Slab:100|Roboto:300|Rock+Salt|Rubik|Satisfy|Slabo+27px|Source+Sans+Pro:600|Unica+One|Varela+Round|Work+Sans

**Comment by Ketcap** [comment]
fontlar dahil edildi
